# Generated by Django 3.0.3 on 2020-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.TextField(null=True),
        ),
    ]
